import { 
  Home, 
  Users, 
  FileText, 
  Scissors, 
  CheckSquare, 
  Banknote, 
  BarChart3, 
  Settings, 
  User,
  PackageCheck,
  CreditCard,
  Trash2
} from 'lucide-react';

export const APP_NAME = 'Kurti ERP';
export const FACTORY_NAME = 'Kurti Manufacturing Factory';
export const API_BASE_URL = 'http://localhost:5000/api';

export const ROUTES = {
  SPLASH: '/',
  LOGIN: '/login',
  HOME: '/home',
  EMPLOYEES: '/employees',
  JOB_CARDS: '/job-cards',
  CUTTING: '/cutting',
  BUNDLES: '/bundles',
  ASSIGNMENT: '/assignment',
  SALARY: '/salary',
  ADVANCES_PAYMENTS: '/advances-payments',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  ARCHIVE: '/archive',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  FORBIDDEN: '/forbidden',
  COMING_SOON: '/coming-soon',
  SUPER_ADMIN_DASHBOARD: '/super-admin/dashboard',
  SUPER_ADMIN_COMPANIES: '/super-admin/companies',
  SUPER_ADMIN_OWNERS: '/super-admin/owners',
  SUPER_ADMIN_USERS: '/super-admin/users',
  SUPER_ADMIN_SETTINGS: '/super-admin/settings',
  SUPER_ADMIN_AUDIT_LOGS: '/super-admin/audit-logs',
};

export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  CUTTING_MASTER: 'CUTTING_MASTER',
};

export const NAVIGATION_ITEMS = [
  // Super Admin Items
  {
    id: 'super_admin_dashboard',
    label: 'Dashboard',
    path: '/super-admin/dashboard',
    icon: 'Home',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: true,
    category: 'Dashboard',
  },
  {
    id: 'super_admin_companies',
    label: 'Companies',
    path: '/super-admin/companies',
    icon: 'Building2',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: true,
    category: 'Management',
  },
  {
    id: 'super_admin_owners',
    label: 'Owners',
    path: '/super-admin/owners',
    icon: 'ShieldCheck',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: true,
    category: 'Management',
  },
  {
    id: 'super_admin_users',
    label: 'Users',
    path: '/super-admin/users',
    icon: 'Users',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: true,
    category: 'Management',
  },
  {
    id: 'super_admin_settings',
    label: 'System Settings',
    path: '/super-admin/settings',
    icon: 'Settings',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: false,
    category: 'Settings',
  },
  {
    id: 'super_admin_audit_logs',
    label: 'Audit Trail',
    path: '/super-admin/audit-logs',
    icon: 'Activity',
    allowedRoles: ['SUPER_ADMIN'],
    mobileBottom: false,
    category: 'Security',
  },

  // Owner/Manager/Cutting Master Items
  {
    id: 'home',
    label: 'Dashboard',
    path: ROUTES.HOME,
    icon: 'Home',
    allowedRoles: ['OWNER', 'MANAGER', 'CUTTING_MASTER'],
    mobileBottom: true,
    category: 'Dashboard',
  },
  {
    id: 'job_cards',
    label: 'Job Cards',
    path: ROUTES.JOB_CARDS,
    icon: 'FileText',
    allowedRoles: ['OWNER', 'MANAGER'],
    mobileBottom: true,
    category: 'Production',
  },
  {
    id: 'cutting',
    label: 'Cutting Queue',
    path: ROUTES.CUTTING,
    icon: 'Scissors',
    allowedRoles: ['OWNER', 'MANAGER', 'CUTTING_MASTER'],
    mobileBottom: true,
    category: 'Production',
  },
  {
    id: 'assignments',
    label: 'Bundle Assignment',
    path: '/assignments',
    icon: 'CheckSquare',
    allowedRoles: ['OWNER', 'MANAGER'],
    mobileBottom: true,
    category: 'Production',
  },
  {
    id: 'employees',
    label: 'Employees Master',
    path: ROUTES.EMPLOYEES,
    icon: 'Users',
    allowedRoles: ['OWNER'],
    mobileBottom: true,
    category: 'Workforce',
  },
  {
    id: 'salary',
    label: 'Salary & Payroll',
    path: ROUTES.SALARY,
    icon: 'Banknote',
    allowedRoles: ['OWNER', 'MANAGER'],
    mobileBottom: false,
    category: 'Workforce',
  },
  {
    id: 'advances_payments',
    label: 'Advances & Ledger',
    path: ROUTES.ADVANCES_PAYMENTS,
    icon: 'CreditCard',
    allowedRoles: ['OWNER', 'MANAGER'],
    mobileBottom: false,
    category: 'Workforce',
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    path: ROUTES.REPORTS,
    icon: 'BarChart3',
    allowedRoles: ['OWNER', 'MANAGER', 'CUTTING_MASTER'],
    mobileBottom: false,
    category: 'Reports',
  },
  {
    id: 'settings',
    label: 'System Settings',
    path: ROUTES.SETTINGS,
    icon: 'Settings',
    allowedRoles: ['OWNER'],
    mobileBottom: false,
    category: 'Settings',
  },
  {
    id: 'archive',
    label: 'Archive / Trash',
    path: ROUTES.ARCHIVE,
    icon: 'Trash2',
    allowedRoles: ['OWNER'],
    mobileBottom: false,
    category: 'Archive',
  },
  {
    id: 'profile',
    label: 'My Profile',
    path: ROUTES.PROFILE,
    icon: 'User',
    allowedRoles: ['OWNER', 'MANAGER', 'CUTTING_MASTER'],
    mobileBottom: false,
    category: 'Profile',
  },
];

export const PRIORITY_OPTIONS = [
  { value: 'NORMAL', label: 'Normal', color: 'blue' },
  { value: 'HIGH', label: 'High', color: 'orange' },
  { value: 'URGENT', label: 'Urgent', color: 'red' },
];

export const JOB_CARD_STATUSES = [
  { value: 'CREATED', label: 'Created', color: 'blue' },
  { value: 'READY_FOR_CUTTING', label: 'Ready for Cutting', color: 'amber' },
  { value: 'CUTTING_IN_PROGRESS', label: 'Cutting In Progress', color: 'indigo' },
  { value: 'CUTTING_COMPLETED', label: 'Cutting Completed', color: 'emerald' },
];

export const DEFAULT_CUTTING_COMPONENTS = [
  'Top',
  'Pant',
  'Top Aster',
  'Pant Aster',
  'Dupatta',
];
